name: PR
on:
  [pull_request]
jobs:
  build:
    permissions: 
      pull-requests: write 
      repository-projects: read
      contents: read
    runs-on: ubuntu-latest
    container:
      image: evanstoddard/palm_toolchain
    steps:
      - uses: actions/checkout@v4
      - run: export PATH=${PATH}:/opt/palm_gnu_tools/bin
      - run: make
